### PR TITLE
Adds token management to init + adds token add script

### PR DESCRIPTION
**Pull request by carsonfarmer**
Still testing 'in the wild', but ready for an initial review.

### CODE REVIEW

**Review by sanderpick — APPROVED** [review]

**Comment by carsonfarmer** [comment]
@sanderpick for this to work 'in the wild' (just tested), you'll need to run the upgrade-all script, and then the add-token-all script. Is this good enough, or would you like a script that does this all in one go? Seems more useful to have them separate?

**Comment by sanderpick** [comment]
did you actually run `upgrade-all.sh` with our keys? note, the cafes are at rc31 now.

**Comment by sanderpick** [comment]
Yeah, separate... upgrading shouldn't create a new token

**Comment by sanderpick** [comment]
test test

**Comment by sanderpick** [comment]
slack test

**Comment by carsonfarmer** [comment]
No haven't upgraded yet, we haven't pushed up the release tag. Will do once we do that.

**Pull request merged**
